### ISSUE TITLE
BasicAPI.UploadMedia有问题

### ISSUE THREAD

**Issue by wzca** [night-king/weixinSDK#1]
BasicAPI.UploadMedia
weixin已经调整了，这里还没改呢。
        public static string UploadMedia(string access_token, string type, string file)
        {
            //var url = string.Format("http://api.weixin.qq.com/cgi-bin/media/upload?access_token={0}&type={1}&filename={2}", access_token, type, Path.GetFileName(file));
            //var client = new HttpClient();
            //var result = client.PostAsync(url, new StreamContent(new FileStream(file, FileMode.Open, FileAccess.Read)));
            //if (!result.Result.IsSuccessStatusCode) return string.Empty;
            //var media = DynamicJson.Parse(result.Result.Content.ReadAsStringAsync().Result);
            //return media.media_id;
            //----------- Change By StephenWang 2015-01-28  微信改为需要Form提交，才能上传
            string wxurl = "http://file.api.weixin.qq.com/cgi-bin/media/upload?access_token=" + access_token + "&type=" + type;
            System.Net.WebClient myWebClient = new System.Net.WebClient();
            myWebClient.Credentials = System.Net.CredentialCache.DefaultCredentials;
            byte[] responseArray = myWebClient.UploadFile(wxurl, "POST", file);
            var result = System.Text.Encoding.Default.GetString(responseArray, 0, responseArray.Length);
            var media = DynamicJson.Parse(result);
            result = media.media_id;
            return result;
        }

**Comment by night-king** [comment]
万分感谢，这个以前的api现在还能用（亲自测试：https://mp.weixin.qq.com/debug/cgi-bin/apiinfo?t=index&type=%E5%9F%BA%E7%A1%80%E6%94%AF%E6%8C%81&form=%E5%A4%9A%E5%AA%92%E4%BD%93%E6%96%87%E4%BB%B6%E4%B8%8A%E4%BC%A0%E6%8E%A5%E5%8F%A3%20/media/upload），稍后会改过来。

**Comment by night-king** [comment]
已经修复，代码提交记录：
https://github.com/night-king/weixinSDK/commit/4d70a0a6ae8f007bf3dd46e75e982febb7cd6c23

如果还有问题，请告知。
