### ISSUE TITLE
DynamicJson序列化问题

### ISSUE THREAD

**Issue by net205** [night-king/weixinSDK#14]
1、定义一模板消息类：
public class TemplateMessageModel
{
//....
public Dictionary<string, TemplateMessageDataModel> data { get; set; }
//....
}

```
public class TemplateMessageDataModel
{
    /// <summary>
    /// 数据项目值
    /// </summary>
    public string value { get; set; }

    /// <summary>
    /// 数据项颜色
    /// 16进制颜色代码(缺省为：#173177)
    /// </summary>
    public string color { get; set; }

    public TemplateMessageDataModel(string value, string color = "#173177")
    {
        this.value = value;
        this.color = color;
    }
}
```

2、实例化后，添加数据
DynamicJson.Serialize(TemplateMessageModelInstance)得到结果是这样：

{
    "touser": "",
    "template_id": "",
    "url": "http://www.baidu.com",
    "topcolor": "#FF0000",
    "data": [
        {
            "Key": "first",
            "Value": {
                "value": "审核结果通知",
                "color": "#173177"
            }
        },
        {
            "Key": "keyword1",
            "Value": {
                "value": "手机号码",
                "color": "#173177"
            }
        },
        {
            "Key": "keyword2",
            "Value": {
                "value": "帐户信息",
                "color": "#173177"
            }
        },
        {
            "Key": "keyword3",
            "Value": {
                "value": "审核状态",
                "color": "#173177"
            }
        },
        {
            "Key": "keyword4",
            "Value": {
                "value": "2015/12/16 19:00:09",
                "color": "#173177"
            }
        },
        {
            "Key": "remark",
            "Value": {
                "value": "备注",
                "color": "#173177"
            }
        }
    ]
}

注：data是个数组

而用Newtonsoft.Json序列化是这样的：
{
    "touser": "",
    "template_id": "",
    "url": "http://www.baidu.com",
    "topcolor": "#FF0000",
    "data": {
        "first": {
            "value": "审核结果通知",
            "color": "#173177"
        },
        "keyword1": {
            "value": "手机号码",
            "color": "#173177"
        },
        "keyword2": {
            "value": "帐户信息",
            "color": "#173177"
        },
        "keyword3": {
            "value": "审核状态",
            "color": "#173177"
        },
        "keyword4": {
            "value": "2015/12/16 19:00:09",
            "color": "#173177"
        },
        "remark": {
            "value": "备注",
            "color": "#173177"
        }
    }
}

应该算一个问题吧？？？？

**Comment by net205** [comment]
换一种方式，定义动态变量，就不存在此问题

**Comment by night-king** [comment]
我这个是Dynamic对象和Json字符串互转，不支持强命名的实体类与Json互转，请用Dynamic！
