### ISSUE TITLE
jssdk签名错误

### ISSUE THREAD

**Issue by stoneniqiu** [night-king/weixinSDK#17]
util中的sha1方法应该是：
 public static string Sha1(string orgStr, Encoding encode)
        {
            SHA1 sha1 = new SHA1CryptoServiceProvider();
            byte[] bytes_in = encode.GetBytes(orgStr);
            byte[] bytes_out = sha1.ComputeHash(bytes_in);
            sha1.Dispose();
            string result = BitConverter.ToString(bytes_out);
            result = result.Replace("-", "");
            return result;  
        }

**Comment by night-king** [comment]
未重新此问题
