### ISSUE TITLE
公众号计划2017/12/30停止http的接口,本项目有没有升级的计划

### ISSUE THREAD

**Issue by chaohui2** [night-king/weixinSDK#19]
公众号计划2017/12/30停止http的接口,本项目有没有升级的计划
[公告](https://mp.weixin.qq.com/cgi-bin/announce?action=getannouncement&key=1505983913&version=5&lang=zh_CN)
> 关于公众平台接口不再支持HTTP方式调用的公告
> 为保证数据传输安全，提高业务安全性，公众平台将不再支持HTTP方式调用。避免影响正常使用中含有HTTP方式调用的服务，请开发者尽快调整，将现有通过HTTP方式调用的切换成HTTPS调用，平台将于2017年12月30日停止对HTTP方式调用的支持。
> 
> 接口调用方式切换成HTTPS调用指导建议：
> 1.后台程序调用api.weixin.qq.com的接口，采用HTTPS方式，连接端口443，修改方法请自行查询各种编程语言对HTTPS的支持。
> 2.HTML页面对api.weixin.qq.com的URL访问，如果是HTTP方式，请直接指定HTTPS方式。
> 3.javascript等编程语言对api.weixin.qq.com的URL访问也请从HTTP方式改为HTTPS方式。
> 微信团队
> 2017年09月21日

**Comment by night-king** [comment]
Https与本SDK没有关系
