### ISSUE TITLE
动态解析XML出错。

### ISSUE THREAD

**Issue by wzca** [night-king/weixinSDK#2]
WeixinExecutor.cs中
case WeixinMessageType.Event:
                    string eventType = message.Body.Event.Value.ToLower();
                    string eventKey = message.Body.EventKey.Value;
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
在某些事件消息中，没有EventKey这个数据时，动态解析xml时会出错。

**Comment by night-king** [comment]
万分感谢，已经解决啦。

**Comment by night-king** [comment]
https://github.com/night-king/weixinSDK/commit/0715b1866013830e26f63cc1269ebd6ce173a989
