### ISSUE TITLE
卡券上传logo时的URL

### ISSUE THREAD

**Issue by wzca** [night-king/weixinSDK#20]
Card.CreateCardAPI.UploadLogo
var url = string.Format("http://api.weixin.qq.com/cgi-bin/uploadimg?access_token={0}", access_token);
// 这其中的 URL 
// HTTP请求方式: POST/FROM
URL:https://api.weixin.qq.com/cgi-bin/media/uploadimg?access_token=ACCESS_TOKEN
// 参见： https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1451025056
2.3.1 上传图片接口

**Comment by wzca** [comment]
CreateCardAPI.cs 中很多地方都是
if (result.IsSuccessStatusCode) return null;
这个是不是写错了。

**Comment by night-king** [comment]
fixed
