### ISSUE TITLE
VS 2019 命名空间“System.Net”中不存在类型或命名空间名“Http”(是否缺少程序集引用?)	

### ISSUE THREAD

**Issue by beibaodong** [night-king/weixinSDK#23]
在网上找了很多方法都没有解决

**Comment by night-king** [comment]
请使用.net framework 4.5，或者手动添加引用 System.Net.Http.

**Comment by night-king** [comment]
已将引用 System.Net.Http.dll引用方式改为直接引用DLL文件。https://github.com/night-king/weixinSDK/commit/21901e31f29e029fd508f404cd8e514251e229c9
