### ISSUE TITLE
又发现一个小错。多了一行没用的？

### ISSUE THREAD

**Issue by wzca** [night-king/weixinSDK#4]
using System.Dynamic;
using System.Xml.Linq;
using System.Xml;
using Codeplex.Data;
using Tencent;
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
这行是多余的吧？

**Comment by night-king** [comment]
using Tencent; 是消息体加密解密功能引用了官方C#版本的AES算法实现。详情请参考：http://weixinsdk.net/forum.php?mod=viewthread&tid=39&extra=

**Comment by wzca** [comment]
学习了。
