### ISSUE TITLE
关于时间戳

### ISSUE THREAD

**Issue by wzca** [night-king/weixinSDK#5]
程序里还有几个地方在使用 DateTime.Now.ToBinary() 生成时间戳，
生成的都是负数，虽说现在腾讯没校验，防止万一，有时间改一下吧。
看到JSAPI里有这样的函数：
/// <summary>

        /// 创建时间戳
        /// </summary>

        /// <returns></returns>
        public static long CreatenTimestamp()
        {
            return (DateTime.Now.ToUniversalTime().Ticks - 621355968000000000) / 10000000;
        }

**Comment by wzca** [comment]
之前说过的那个UploadMedia函数，我试了一下，好象真是有问题。返回(41005)缺少多媒体文件数据

**Comment by night-king** [comment]
时间戳已改，UploadMedia稍后，会在issue#1回复。

**Comment by night-king** [comment]
代码提交记录：https://github.com/night-king/weixinSDK/commit/26fd1aee8315f70967476df3ce46a4a33954fb90
