### ISSUE TITLE
例子里有个笔误，我说怎么总生成日志呢。

### ISSUE THREAD

**Issue by wzca** [night-king/weixinSDK#8]
case "location"://上报地理位置事件
                            #region 上报地理位置事件
                            var lat = message.Body.Latitude.Value.ToString();
                            var lng = message.Body.Longitude.Value.ToString();
                            var pcn = message.Body.Precision.Value.ToString();
                            //TODO:在此处将经纬度记录在数据库,这里用log4net记录日志
                            LogWriter.Default.WriteInfo(string.Format("openid:{0} ,location,lat:{1},lng:{21},pcn:{3}", openId, lat, lng, pcn));
                            #endregion
##                             break;

lng:{21} ......2啊

**Comment by night-king** [comment]
fixed by https://github.com/night-king/weixinSDK/commit/2dd66ada7e63dc5227be623edb47aef65b67e901
