### ISSUE TITLE
发送模板消息函数好象有点问题

### ISSUE THREAD

**Issue by wzca** [night-king/weixinSDK#9]
/// <summary>

        /// 发送模板消息
        /// 在模版消息发送任务完成后，微信服务器会将是否送达成功作为通知，发送到开发者中心中填写的服务器配置地址中。
        /// 参见WeixinExecutor.cs TEMPLATESENDJOBFINISH Event
        /// </summary>

        /// <param name="access_token"></param>
        /// <param name="content">模板消息体,由于模板众多,且结构不一，请开发者自行按照模板自行构建模板消息体,模板消息体为json字符串,请登录微信公众号后台查看</param>
        /// <returns>  { "errcode":0,"errmsg":"ok", "msgid":200228332}
        /// </returns>
        public static dynamic SendTemplateMessage(string access_token, dynamic content)
        {
            var url = string.Format("https://api.weixin.qq.com/cgi-bin/message/template/send?access_token={0}", access_token);
            var client = new HttpClient();
            var result = client.PostAsync(url, new StringContent(DynamicJson.Serialize(content))).Result;
            return DynamicJson.Parse(result.Content.ReadAsStringAsync().Result);
        }

---

DynamicJson.Serialize
这个的作用是什么呢?  传了json串后。就出错了。。。返回。47001 data format error
我把这个去掉，就正常了。

**Comment by night-king** [comment]
DynamicJson.Serialize是把动态对象（Dynamic）转成字符串形式的json对象，这个是本SDK的核心和精髓。
官方解释：http://mp.weixin.qq.com/wiki/17/fa4e1434e57290788bde25603fa2fcbd.html
47001   解析JSON/XML内容错误, 
我估计是你的参数：content不符合api的约定，请按照官方文档那样build数据。

参考：
http://mp.weixin.qq.com/wiki/17/304c1885ea66dbedf7dc170d84999a9d.html
